// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Post struct {
	ID             int64
	Content        sql.NullString
	UserID         int64
	OriginalPostID sql.NullInt64
	CreatedAt      time.Time
}

type User struct {
	ID        int64
	Username  string
	CreatedAt time.Time
}
