// Code generated by sqlc. DO NOT EDIT.
// source: posts.sql

package db

import (
	"context"
	"database/sql"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts(
    content, user_id, original_post_id
) VALUES (
    $1, $2, $3
) RETURNING id, content, user_id, original_post_id, created_at
`

type CreatePostParams struct {
	Content        sql.NullString `json:"content"`
	UserID         int64          `json:"user_id"`
	OriginalPostID sql.NullInt64  `json:"original_post_id"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.Content, arg.UserID, arg.OriginalPostID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.UserID,
		&i.OriginalPostID,
		&i.CreatedAt,
	)
	return i, err
}
