// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	SeedPost(ctx context.Context, arg SeedPostParams) (Post, error)
	SeedUser(ctx context.Context, username string) (int64, error)
}

var _ Querier = (*Queries)(nil)
