// Code generated by sqlc. DO NOT EDIT.
// source: users.sql

package db

import (
	"context"
)

const seedUser = `-- name: SeedUser :one
INSERT INTO users(username) VALUES ($1) returning id
`

func (q *Queries) SeedUser(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, seedUser, username)
	var id int64
	err := row.Scan(&id)
	return id, err
}
