// Code generated by sqlc. DO NOT EDIT.
// source: users.sql

package db

import (
	"context"
)

const seedUsers = `-- name: SeedUsers :exec
INSERT INTO users(id, username) VALUES
    (1, 'fferdinand'),
    (2, 'fjosef'),
    (3, 'sissi'),
    (4, 'maximilian')
`

func (q *Queries) SeedUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, seedUsers)
	return err
}
